apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sts-secret
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name:  ${NAME}
      namespace: ${NAMESPACE}
    type: Opaque
    stringData:
      credentials: |
        [default]
        role_arn = ${ROLE_ARN}
        web_identity_token_file = ${WEB_IDENTITY_TOKEN_FILE}
      role_arn: ${ROLE_ARN}
parameters:
  - name: NAME
    required: true
  - name: NAMESPACE
    required: true
  - name: ROLE_ARN
    value: arn:aws:iam::123456789012:role/example
  - name: WEB_IDENTITY_TOKEN_FILE
    value: /var/run/secrets/openshift/serviceaccount/token
