codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: down
  range: "20...100"
  ignore:
    - "make"
    - "config"
    - "openshift-ci"
    - "bundles"
    - "deploy"
    - "envs"
    - "guides"
    - "hack"
    - "manifests"
    - "packagemanifests"
    - "prodsec-manifests"
    - "products"
    - "templates"
    - "test-cases"
    - "test-dependancy"
    - "tmp"
    - "vendor"
    - "version"
    - "test"
    - "**/*_types.go"
    - "**/*_moq.go"
    - "pkg/config"
    - "pkg/metrics"

  status:
    project:
      default:
        target: auto
        threshold: 0%
    patch: false
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
